name: Chris Tremblay
title: Helping developers build awesome stuff on Azure
logo: "https://christremblay.com/images/chris_tremblay_thumbnail_large.jpg"
description: >
 <a href="https://www.linkedin.com/in/chris-tremblay-0536a23/" target="_blank">LinkedIn</a> 
 <br>
 <a href="mailto:chtrembl@microsoft.com">chris.tremblay@microsoft.com</a>
 <br>
 <a href="https://christremblay.com" target="_blank">christremblay.com</a> 
 <br>
 <a href="https://azurepetstore.com" target="_blank">azurepetstore.com</a> 
theme: jekyll-theme-minimal
google_analytics: UA-57469708-2 # your Google Analytics tracking ID here
